version: '3'
services:
  my_mariadb:
    image: mariadb:5.5.64
    restart: always
    ports:
      - ${MARIADB_HOST_PORT}:3306
    volumes:
      - ${PWD}/mariadb/conf.d:/etc/mysql/conf.d
      - ${PWD}/mariadb/data:/var/lib/mysql
#     copy该目录下sql,由docker-entrypoint-initdb.d 中的脚本调用
      - ${PWD}/sys4/ddl-sql:/opt/sql
#      该目录下sql,按照字母顺序，依次执行
      - ${PWD}/sys4/init-sql/create-schema.sql:/docker-entrypoint-initdb.d/1_create-schema.sql
      - ${PWD}/sys4/init-sql/update-sys4-client.sh:/docker-entrypoint-initdb.d/2_update-sys4-client.sh
    environment:
      MYSQL_ROOT_PASSWORD: root123
      LANG: C.UTF-8
      SSO_UPDATE_SYS4_INNER_URL: ' update sys_client a set a.outter_url="http://${HOST_IP}:${NGINX_HOST_PORT}/web-sys4" where a.CLIENT_ID="2135E3D00337471783D6AF46BD43CE4B" ;'
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--lower_case_table_names=1',
      '--default-time-zone=+8:00'
    ]
  my_redis:
    image: redis
    restart: always
    ports:
      - ${REDIS_HOST_PORT}:6379
    volumes:
      - ${PWD}/redis/data:/usr/local/etc/redis/data
    command: redis-server --appendonly yes
  my_ngx:
    image: nginx
    restart: always
    ports:
      # 唯一暴露nginx端口:
      - ${NGINX_HOST_PORT}:${NGINX_HOST_PORT}
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${PWD}/nginx/html:/usr/share/nginx/html:ro
      - ${PWD}/nginx/log:/var/log/nginx
    links:
      #       依赖 sys3后台服务
      - authentication_center
      - sys4
  authentication_center:
    build:
      context: ${PWD}/authentication_center
      dockerfile:  authentication_center.dockerfile
    image: uam-authentication_center:0.0.1
    restart: always
    ports:
    -  ${AUTHENTICATION_CENTER_HOST_PORT}:9011
    volumes:
    - ${PWD}/authentication_center/logs:/app/logs
    links:
      - my_redis:my_redis_alias
    command: --spring.redis.host=my_redis_alias  --spring.datasource.url="jdbc:mysql://my_mariadb:3306/sys3_db?useUnicode=true&characterEncoding=utf-8"
  sys4:
    build:
      context: ${PWD}/sys4
      dockerfile:  sys4.dockerfile
    image: sys4_service:0.0.1
    restart: always
    ports:
      - ${SYS4_HOST_PORT}:9010
    volumes:
      - ${PWD}/sys4/logs:/app/logs
    links:
      - my_mariadb
      - authentication_center:acs
    command: --oauth2.base-url="http://acs:9011" --spring.datasource.url="jdbc:mysql://my_mariadb:3306/sys3_db?useUnicode=true&characterEncoding=utf-8"



